import type { Metadata } from "next";
import { Rethink_Sans } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@splitvanced/tw-class/tw-utils";

const sans = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "block",
  variable:"--font-text",
  adjustFontFallback: false,
});

const heading=Rethink_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "block",
  variable:"--font-heading",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("dark", sans.className,sans.variable,heading.variable)}>{children}</body>
    </html>
  );
}
